name: build

on: push

jobs:
  generate-files:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ linux ]
        arch: [ "arm", "arm64", "386", "amd64" ]
        version: [
          "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30"]
    name: Generate files for ${{ matrix.os }} ${{ matrix.arch }} ${{ matrix.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Generate files
        run: |
          go run main.go
        env:
            ARCH: ${{ matrix.arch }}
            OS: ${{ matrix.os }}
      - name: Upload files
        uses: actions/upload-artifact@v4
        with:
          path: ${{ github.workspace }}/out/file_${{ matrix.os }}_${{ matrix.arch }}_?.txt
          name: file_${{ matrix.os }}_${{ matrix.arch }}_${{ matrix.version }}.txt

  poll-artifacts:
    runs-on: ubuntu-latest
    needs: generate-files
    steps:
      - uses: actions/checkout@v2
      - name: Poll build artifacts
        run: |
          ./.github/scripts/getArtifacts.sh ${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_TOKEN }}
