name: build

on: push

jobs:
  download-and-upload-artifacts:
    runs-on: ubuntu-latest

    name: Download artifacts from releases site
    steps:
      - uses: actions/checkout@v2
      - name: Download artifacts from releases site
        run: |
          ./.github/scripts/downloadArtifacts.sh
      - name: Upload files
        uses: actions/upload-artifact@v4
        with:
          path: ${{ github.workspace }}/artifacts
      - name: Poll artifacts
        run: |
          ./.github/scripts/getArtifacts.sh ${{ github.run_id }}
        env:
            GITHUB_TOKEN: ${{ secrets.TEST_TOKEN }}

#  poll-artifacts:
#    runs-on: ubuntu-latest
#    needs: download-and-upload-artifacts
#    steps:
#      - uses: actions/checkout@v2
#      - name: Poll build artifacts
#        run: |
#          ./.github/scripts/getArtifacts.sh ${{ github.run_id }}
#        env:
#          GITHUB_TOKEN: ${{ secrets.TEST_TOKEN }}
