name: build

on: push

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix-combinations: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - name: Download artifacts from releases site
        run: |
          ./.github/scripts/downloadArtifacts.sh
      - id: set-matrix
        run: |
          ./.github/scripts/matrix.sh "artifacts"

  download-and-upload-artifacts:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        filename: ${{ fromJson(needs.setup.outputs.matrix-combinations) }}
    steps:
      - uses: actions/checkout@v2
      - name: Download artifacts from releases site
        run: |
          ./.github/scripts/downloadArtifacts.sh
      - name: Upload files
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.filename }}
          path: ${{ github.workspace }}/artifacts/${{ matrix.filename }}
      - name: Poll artifacts
        run: |
          ./.github/scripts/getArtifacts.sh ${{ github.run_id }}
        env:
            GITHUB_TOKEN: ${{ secrets.TEST_TOKEN }}

#  poll-artifacts:
#    runs-on: ubuntu-latest
#    needs: download-and-upload-artifacts
#    steps:
#      - uses: actions/checkout@v2
#      - name: Poll build artifacts
#        run: |
#          ./.github/scripts/getArtifacts.sh ${{ github.run_id }}
#        env:
#          GITHUB_TOKEN: ${{ secrets.TEST_TOKEN }}
